export const errorCodeConstants = {
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
    USER_NOT_CREATED: "USER_NOT_CREATED",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    TOKEN_BLACKLISTED: "TOKEN_BLACKLISTED",
};
